const initialInserts = {
    usuario: `
        INSERT INTO usuario (nome_usuario, email_usuario, senha_usuario, diretoria_usuario, permissao_usuario, admin_usuario, userPhoto) VALUES 
            ("admin", "admin@api.com", "123456789", 0, "4", 1, "https://images.unsplash.com/photo-1583957723119-330fc2738e64?q=80&w=2157&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
            ("Juliano", "juliano@gmail.com", "123456789", 0, "2", 0, "https://raw.githubusercontent.com/Equipe-FULLSTACK/API-4/main/readme/juliano.png"),
            ("Thiago", "thiago@gmail.com", "123456789", 0, "3", 0, "https://raw.githubusercontent.com/Equipe-FULLSTACK/API-4/main/readme/thiago.png"),
            ("Leonardo", "leo@gmail.com", "123456789", 0, "3", 0, "https://raw.githubusercontent.com/Equipe-FULLSTACK/API-4/main/readme/leo.jpg"),
            ("Willians", "will@gmail.com", "123456789", 0, "2", 0, "https://raw.githubusercontent.com/Equipe-FULLSTACK/API-4/main/readme/will.png"),
            ("Pedro", "pedro@gmail.com", "123456789", 0, "3", 0, "https://raw.githubusercontent.com/Equipe-FULLSTACK/API-4/main/readme/pedro.png"),
            ("usuario07", "user07@gmail.com", "123456789", 0, "3", 0, "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
            ("usuario08", "user08@gmail.com", "123456789", 0, "2", 0, "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=2080&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
            ("usuario09", "user09@gmail.com", "123456789", 0, "2", 0, "https://plus.unsplash.com/premium_photo-1675130119373-61ada6685d63?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
            ("usuario10", "user10@gmail.com", "123456789", 0, "1", 0, "https://images.unsplash.com/photo-1615813967515-e1838c1c5116?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
            ("usuario11", "user11@gmail.com", "123456789", 1, "1", 0, "https://https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"),
            ("usuario12", "user12@gmail.com", "123456789", 1, "1", 0, "https://images.unsplash.com/photo-1573497019418-b400bb3ab074?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D");
    `,
    produtos: `
        INSERT INTO produto (id, name, image, description, purchasePrice, salePrice, stock, minStock, category, stockLocation, status) VALUES
            (1, "Kit Amaciante", "/src/assets/img/produtos/Combo/KitAmaciante.png", "Kit Amaciante Ypê Concentrado Alquimia Liberdade + Inspiração 500ml Cada 50% de Desconto na 2a Unid", 6.00, 12.25, 58, 10, "Combo", "SJC", true),
            (2, "Kit Minuano", "/src/assets/img/produtos/Combo/KitMinuano.png", "Kit Lava Roupas Pó Roxo 1,6Kg e Amaciante Rosa 2L", 12.00, 24.22, 60, 10, "Combo", "TBT", true),
            (3, "Kit Natura", "/src/assets/img/produtos/Combo/KitNatura.png", "O Presente Natura Tododia Macadâmia é uma verdadeira demonstração de carinho e afeto. Ele traz um ritual completo de limpeza, hidratação e perfumação na fragrância cremosa e confortável de Tododia Macadâmia. Contém itens essenciais para o cuidado de Tododia, incluindo o Sabonete em Barra Puro Vegetal, o Creme Desodorante Nutritivo para o Corpo e o Body Splash Desodorante Colônia. Acompanha uma sacola especial de presente. Conteúdo: 1 Body splash desodorante colônia 200 ml. 1 Creme desodorante nutritivo para o corpo 400 ml. 1 Caixa de sabonetes em barra puro vegetal com 5 unidades de 90 g cada. 1 Sacola especial de presente M.", 50.00, 114.90, 12, 5, "Combo", "JAC", true),
            (4, "COCA garrafa", "/src/assets/img/produtos/Bebida/Coca.png", "É hora de celebrar a união de duas potências icônicas dos quadrinhos e dos refrigerantes: Marvel e Coca-Cola. Desfrute da magia e de todo o sabor de Coca-Cola Original 220ml em uma colaboração épica Mergulhe em um mundo de heróis e vilões enquanto desfruta da refrescância única da Coca-Cola Original 220ml. Esta edição limitada traz uma experiência totalmente nova para os fãs do Universo Marvel.", 1.00, 1.99, 200, 50, "Bebida", "SJC", true),
            (5, "FANTA lata", "/src/assets/img/produtos/Bebida/Fanta.png", "A Fanta é um refrigerante popular conhecido por seu sabor doce e frutado, geralmente disponível em vários sabores, sendo o mais comum o de laranja.", 1.20, 2.25, 300, 50, "Bebida", "TBT", true),
            (6, "Heineken garrafa", "/src/assets/img/produtos/Bebida/Heineken.png", "Heineken é uma cerveja lager Puro Malte, refrescante e de cor amarelo-dourado, produzida com ingredientes 100% naturais: água, malte e lúpulo. Durante o processo de fermentação da Heineken, a exclusiva Levedura A é responsável pelo sabor característico e bem equilibrado, com notas frutadas sutis. A cerveja é fabricada em tanques horizontais para mais sabor e consistência. É por isso que nenhuma outra cerveja tem o gosto de Heineken. Na icônica versão em Long Neck de 330ml (6 unidades), ela possui teor alcoólico de 5% e a temperatura ideal de consumo é de 3º a 5º. A Heineken foi criada para ser a melhor cerveja do mundo desde 1873. Algumas coisas são boas demais para mudar! A lager é mais leve e combina bem com hambúrguer, comida mexicana, queijos e castanhas.", 3.50, 6.79, 600, 100, "Bebida", "JAC", true),
            (7, "Batata congelada", "/src/assets/img/produtos/Porcao/BatataFritaCongelada.png", "A batata corte fino 7mm McCain é congelada, pré frita e já com corte em formato palito com espessura de 7mm.", 15.00, 30.56, 68, 20, "Porção", "SJC", true),
            (8, "Asinha Frango", "/src/assets/img/produtos/Porcao/AsinhaFrango.png", "Coxinha da Asa de Frango Congelada, da marca Sadia, em embalagem com 1 quilo. Parte da linha Bio, provém de aves criadas sem o uso de antibióticos e com alimentação 100% vegetal, o que auxilia em sua qualidade. O corte, que é retirado da parte superior da asa do frango, possui textura macia e conta com osso. Com pele e sabor delicado, traz equilíbrio entre a quantidade de carne e gordura. Quanto às possibilidades de preparo, a coxinha da asa pode ser cozida, grelhada, assada ou frita, adaptando-se aos mais variados gostos e estilos de culinária. É uma opção perfeita para churrascos, petiscos, pratos principais ou até mesmo para compor receitas mais elaboradas, como ensopados e assados. Fonte de proteínas, também é rica em vitaminas do complexo B e em minerais diversos, como fósforo, por exemplo. Sua porção de 100 gramas possui, aproximadamente, valor energético de 128 kcal, 14 gramas de proteínas, 5,4 gramas de gorduras totais e 58 miligramas de sódio. Para conservar o alimento, é recomendado mantê-lo congelado, em temperatura de -12oC ou mais frio. Dessa forma, são preservadas as características do produto e mantida sua segurança alimentar.", 13.00, 27.25, 20, 5, "Porção", "CPV", true),
            (9, "Bolinho Bacalhau", "/src/assets/img/produtos/Porcao/BolinhoBacalhau.png", "Os Bolinhos com Bacalhau Seara são feitos com bacalhau nobre, seguindo a tradicional receita portuguesa. Práticos para fazer no dia a dia, seja no almoço ou no jantar, ou até mesmo servir como aperitivo naquelas ocasiões especiais. Além de ser saboroso e irresistível, é muito fácil de preparar e fica pronto em poucos minutos, inclusive você também pode fazer o bolinho de bacalhau Frito ou assado, é uma delícia!", 16.00, 32.50, 20, 5, "Porção", "SJC", true);
    `
};

module.exports = initialInserts;
